[server]
headless = true

[theme]
base="dark"
primaryColor="#000000"  # Twitch Purple for primary highlights
backgroundColor="#570082"  # Light gray background
secondaryBackgroundColor="#570082"  # Dark purple for sidebar background
textColor="#FFFFFF"
font="sans serif"  # Techno-vibe font

[main]
mainPageName = "Intro"



